@startwbs CSP-Directives
*[#FFFFDD] [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy directives]]
** [[https://developer.mozilla.org/en-US/docs/Glossary/Fetch_directive fetch]]
+++ [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src connect-src]]
---[#pink] [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/default-src default-src]]
*** [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/font-src font-src]]
--- [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src frame-src]]
*** [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src img-src]]
--- [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/manifest-src manifest-src]]
*** [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/media-src media-src]]
--- [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/object-src object-src]]
*** [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/prefetch-src prefetch-src]] <:test_tube:>
--- [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src script-src]]
*** [[ script-src-elem]]
--- [[ script-src-attr]]
*** [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src style-src]]
--- [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src-elem style-src-elem]]
*** [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src-attr style-src-attr]]
--- [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src worker-src]]
** document
*** [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/base-uri base-uri]]
*** [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/sandbox sandbox]]
** navigation
*** [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/form-action form-action]]
*** [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors frame-ancestors]]
*** [[ navigate-to]] <:test_tube:>
** reporting
*** [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to report-to]] <:warning:>
*** [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-uri report-uri]] <:recycle:>
** other
*** [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/upgrade-insecure-requests upgrade-insecure-requests]]
*** [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-trusted-types-for require-trusted-types-for]] <:test_tube:>
*** [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/trusted-types trusted-types]] <:test_tube:>
@endwbs