@startwbs CSP-Directives
*[#FFFFDD] directives
** fetch
+++ connect-src
---[#pink] default-src
*** font-src
--- frame-src
*** img-src
--- manifest-src
*** media-src
--- object-src
*** prefetch-src <:test_tube:>
--- script-src
*** script-src-elem
--- script-src-attr
*** style-src
--- style-src-elem
*** style-src-attr
--- worker-src
** document
*** base-uri
*** sandbox
** navigation
*** form-action
*** frame-ancestors
*** navigate-to <:test_tube:>
** reporting
*** report-to <:warning:>
*** report-uri <:recycle:>
** other
*** upgrade-insecure-requests
*** require-trusted-types-for <:test_tube:>
*** trusted-types <:test_tube:>
@endwbs